# coding: utf-8
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'APNApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for APNApp
  pod 'Helpshift', ‘7.9.0’

end
